### ISSUE TITLE
Not able to get it to run

### ISSUE THREAD

**Issue by jim-at-jibba** [sultanahamer/nvim-dap-reactnative#1]
Hey bud,

Thanks for this plugin. I am so excited by it. I cant seem to get it to attach. I have followed the instructions but get an error the node2 is not responding. I dont get the white screen when running the android app. 

node2 works in other environments (node).

I realise this is not a lot to go on, just wondered if you had any toughts.

Thanks

**Comment by sultanahamer** [comment]
@jim-at-jibba we can do a zoom call on this to debug and see what could be the problem on or after Monday IST. let me know a suitable time.

Since this is not a right away easier setup and also nvim-dap has been rewritten after I created this plugin, we will have to consider all those.

**Comment by jim-at-jibba** [comment]
Hey dude,

That would be awesome thanks. I will a blog post after detailing the setup. Maybe we could add that to the repos readme. 

I'm free all next week. I'm GMT so  name a time that suits you

**Comment by sultanahamer** [comment]
@jim-at-jibba I tried running it again on my local. Here are somethings you might need to know.

```
M.config = {
	adapters = {
		type = "executable",
		command = "node",
		args = { dbg_path .. "vscode-node-debug2/out/src/nodeDebug.js" },
	},
	configurations = {
		{
			type = "node2",
			request = "attach",
			program = "${file}",
			cwd = fn.getcwd(),
			sourceMaps = true,
			protocol = "inspector",
			console = "integratedTerminal",
			port = 35000
		},
	},
}
```
In the config specified above from readme.md, `port: 35000` and `request: attach` are somethings that might get missed often

Also, I have installed the debuggers using DAPInstall plugin which is now renamed to dap-buddy https://github.com/Pocco81/dap-buddy.nvim

Last time I checked it was under migration. You can try to point it to branch `dev` for pre-migration code.

**Comment by sultanahamer** [comment]
@jim-at-jibba If I understand your timezone info, its GMT 0.00 which is 5.30 hours behind us. So, we can try this at 11.00 AM your time today if you are available which will be 16:30 our time.

Will ping a zoom meeting id 5 mins before meeting

**Comment by jim-at-jibba** [comment]
Hey bud,

I have my config the same except it's set up to configure against typescriptreact. I will post my config here when I am at my computer. 

Thanks for the zoom meet offer. I keep weekends for family so won't.m be at my computer. Can we do 11am GMT on Monday?

**Comment by sultanahamer** [comment]
Sure. Will post zoom meeting id at that time. In case you start your day earlier on Monday, do let me know what time works for you.

**Comment by jim-at-jibba** [comment]
I am available anytime now, thanks

**Comment by sultanahamer** [comment]
@jim-at-jibba will schedule a call in within 20 to 30 minutes.

**Comment by jim-at-jibba** [comment]
Thanks

**Comment by sultanahamer** [comment]
@jim-at-jibba try to join this meeting id: https://thoughtworks.zoom.us/j/99858017317

**Comment by sultanahamer** [comment]
@jim-at-jibba Removed the zoom id. You can send a pr on the documentation part of "Enable debug mode on the app in emulator" when you find time. It would be great to have the documentation from the language of a consumer.

Also feel free to reword the steps in documentation. I am not a native English speaker so the language and words used might feel odd.

**Comment by felipejoribeiro** [comment]
Hey guys, just saw  the thread, great to see things going. I would love to help too, if you need anything hit me up.

**Comment by sultanahamer** [comment]
We had a connect offline and fixed the issue in @jim-at-jibba setup. We need to update documentation with "Enable the debug in the react native app in emulator/mobile" step

**Comment by jim-at-jibba** [comment]
I will try to update the docs soon. I will also try and write a quick blog post to accompany the repo. 

@sultanahamer thanks again for your help today! So helpful

**Comment by jim-at-jibba** [comment]
PR submitted. Thanks
